/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.*;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import factory.ConnectionFactory;
import dao.PesquisaUsuarioDAO;
import dao.ExcluiUsuarioDAO;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;




/**
 *
 * @author willian.batista
 */
public class PesquisarUsuario extends javax.swing.JFrame {
    
    JButton botao_alterar;
    JButton botao_Excluir;
    JButton botao_pesquisar;
    JButton botao_proxima_pagina;
    JButton botao_pagina_anterior;
    JTextField busca_nome;  
    JTextField busca_cpf;
    JTextField pagina_atual;
    JLabel texto_busca_nome;
    JLabel texto_busca_cpf;
    JLabel texto_busca_status;
    JLabel texto_pagina_atual;
    ImageIcon icone;
    ImageIcon proxima_pagina;
    ImageIcon pagina_anterior;
    JComboBox comboStatus = new JComboBox();
    public int pagina = 1 ;
    
    static Vector<Vector<String>> data=new Vector<Vector<String>>();
    static JTable table;
    private JButton botao;
    public String codigo_usuario ;
    
    
    private JTable listUsuarios;
    private JScrollPane scrollpane;
    Container tela = getContentPane();

    /**
     * Creates new form PesquisarUsuario
     */
    public PesquisarUsuario() {
        initComponents2();
         Chama_Tabela();
    }
    
    
     private void Chama_Tabela() {
        

        //Pesquisa de Usuarios
        PesquisaUsuarioDAO dao = new PesquisaUsuarioDAO();
        data = dao.getDataUsuarios(busca_nome.getText(),busca_cpf.getText(),(String)comboStatus.getSelectedItem(),pagina);
        
        
        //Define as colunas da tabela
        Vector<String> headers=new Vector<String>();
        headers.add("id");
        headers.add("Nome");
        headers.add("CPF");
        headers.add("E-mail");
        
      
        DefaultTableModel model = new DefaultTableModel(data, headers);
        
        //define a tabela como tendo 3 colunas
        JTable listUsuarios = new JTable(model);
        JScrollPane scrollpane = new JScrollPane(listUsuarios);
        
        
        //Monta a
        JPanel topPanel=new JPanel();
        getContentPane().add(topPanel,BorderLayout.NORTH);
        
        JScrollPane scroll = new JScrollPane(table);
        scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        scrollpane.setBounds(50,150,700,450);
        tela.add(scrollpane);
        
        
        
         
         
      //  listUsuarios.setCellSelectionEnabled(false);
     
        
        
        ListSelectionModel cellSelectionModel = listUsuarios.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
          public void valueChanged(ListSelectionEvent e) {
            
   
            int[] linha_selecionada = listUsuarios.getSelectedRows();
            
            for (int i = 0; i < linha_selecionada.length; i++) {
            for (int j = 0; j < linha_selecionada.length; j++) {
              codigo_usuario = (String) listUsuarios.getValueAt(linha_selecionada[i], 0);
              }
            }

          }

        });  

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     
  
     
    
     private void initComponents2() {

        //Tamanho Da Janela
        //super("Pesquisa de Usuários");
        setLayout(null);
        
      

        
        //label busca nome
        texto_busca_nome = new JLabel("Nome:");
        texto_busca_nome.setBounds(50,50,300,30);
        tela.add(texto_busca_nome);
        
        //campo busca nome
        busca_nome = new JTextField("");
        busca_nome.setBounds(100,50,180,25);
        //busca_nome.setSize(200, 180);
        tela.add(busca_nome);
        
        
        //campo busca CPF
        texto_busca_cpf = new JLabel("CPF:");
        texto_busca_cpf.setBounds(300,50,400,25);
        tela.add(texto_busca_cpf);
        
        
         //campo busca nome
        busca_cpf = new JTextField("");
        busca_cpf.setBounds(335,50,120,25);
        //busca_nome.setSize(200, 180);
        tela.add(busca_cpf);
        
        
        
        
         //campo busca CPF
        texto_busca_status = new JLabel("Status:");
        texto_busca_status.setBounds(480,50,400,25);
        tela.add(texto_busca_status);
        
        
        
        //Cria o select menu
        //icone = new ImageIcon("abrir.gif");
        comboStatus = new JComboBox ();
        comboStatus.setBounds(530,49,110,25);
        tela.add(comboStatus);
        comboStatus.addItem("Ativo"); 
        comboStatus.addItem("Inativo");
        
        
        //Cria o botão Pesquisar
        icone = new ImageIcon("src/imagens/pesquisa.jpg");
        botao_pesquisar = new JButton (icone);
        botao_pesquisar.setBorderPainted(false); 
        botao_pesquisar.setBounds(670,45,35,32);
        tela.add(botao_pesquisar);
        
        
        
        //Cria o botão Proxima pagina
        proxima_pagina = new ImageIcon("src/imagens/proxima_pagina.jpg");
        botao_proxima_pagina = new JButton (proxima_pagina);
        botao_proxima_pagina.setBorderPainted(false); 
        botao_proxima_pagina.setBounds(710,612,35,32);
        tela.add(botao_proxima_pagina);
        
        
        

         botao_proxima_pagina.addActionListener(
                new ActionListener(){
                    public void actionPerformed(ActionEvent e){
                        pagina++;
                        pagina_atual.setText(String.valueOf(pagina)); 
                         Chama_Tabela();
                      
                    }
                }
        );
                    




        //Cria o botão Proxima pagina
        pagina_anterior = new ImageIcon("src/imagens/pagina_anterior.jpg");
        botao_pagina_anterior = new JButton (pagina_anterior);
        botao_pagina_anterior.setBorderPainted(false); 
        botao_pagina_anterior.setBounds(625,613,35,32);
        tela.add(botao_pagina_anterior);
        
        
         botao_pagina_anterior.addActionListener(
                new ActionListener(){
                    public void actionPerformed(ActionEvent e){
                        if(pagina>1){
                        pagina--;
                        pagina_atual.setText(String.valueOf(pagina)); 
                         Chama_Tabela();
                        }
                    }
                }
        );
        
        
        
        //label pagina
        texto_pagina_atual = new JLabel("Pagina:");
        texto_pagina_atual.setBounds(665,590,300,30);
        tela.add(texto_pagina_atual);
        
        

       
         //campo busca nome
        pagina_atual = new JTextField(String.valueOf(pagina));
        pagina_atual.setBounds(663,613,45,30);
        //busca_nome.setSize(200, 180);
        tela.add(pagina_atual);
        
        
        
        
        botao_pesquisar.addActionListener(
                new ActionListener(){
                    public void actionPerformed(ActionEvent e){
                        Chama_Tabela();
                    }
                }
        );
        



        
        //Cria o botão alterar
        //icone = new ImageIcon("abrir.gif");
        botao_alterar = new JButton ("Alterar");
        botao_alterar.setBounds(230,650,100,30);
        tela.add(botao_alterar);
        
        
         botao_alterar.addActionListener(
                new ActionListener(){
                    public void actionPerformed(ActionEvent e){
                        new AlteraUsuarios().AlteraUsuarios(codigo_usuario);
                        
                    }
                }
        );
        
         
         
         
        
        
        
        //Cria o botão excluir
        botao_Excluir = new JButton ("Excluir");
        botao_Excluir.setBounds(400,650,100,30);
        tela.add(botao_Excluir);
        
        botao_Excluir.addActionListener(
                new ActionListener(){
                    public void actionPerformed(ActionEvent e){
                        botao_Excluir();
                    }
                }
        );
        
        
            
        getRootPane().setDefaultButton(botao_pesquisar);  
        
        
        //Cria o tamanho da janela
        setSize(800, 800);
        setVisible(true);
        setLocationRelativeTo(null);
    }// </editor-fold> 
    
      public void botao_Excluir() {                                               
        ExcluiUsuarioDAO alunobd = new ExcluiUsuarioDAO();
        
  
    
        if (JOptionPane.showConfirmDialog(rootPane, "Confirma exclusão?", "Confirmação de exlusão de Aluno", 1, 1)==0){
            if (alunobd.Deleta_Usuario(codigo_usuario)){
                JOptionPane.showMessageDialog(this,"Excluido com sucesso!", "Manutenção de Aluno",1);
            }else {
                JOptionPane.showMessageDialog(this, "Exclusão não realizada!", "Manutenção de Aluno", 0);
            }
            Chama_Tabela(); 
        } else {
            JOptionPane.showMessageDialog(this, "Exclusão cancelada pelo usuário!", "Manutenção de Aluno", 0);
        }

    }           
    
      
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarUsuario().setVisible(true);
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
